# Generated by Django 3.1.7 on 2021-03-13 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='title',
            new_name='term',
        ),
    ]
