# Generated by Django 4.2.10 on 2024-03-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0002_auto_20210314_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Категориянын аты'),
        ),
    ]
