# Generated by Django 3.1.7 on 2021-03-14 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0002_auto_20210314_0455'),
        ('like', '0002_auto_20210314_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestionslikes', to='like.like')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestionslikes', to='term.suggestion')),
            ],
        ),
    ]
